spring:
  application:
    name: shellDemo
  main:
    web-application-type: NONE
    banner-mode: OFF
  shell:
    interactive:
      enabled: true
    script:
      enabled: true
    history:
      enabled: false

logging:
  level:
    root: OFF
