name: Build Native Windows

on:
  push:
    branches: [ master ]

jobs:
  build-native:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: "21.0.0"
          java-version: "21"
          distribution: "graalvm"
          components: 'native-image'

      - name: Build Native Image
        run: ./gradlew nativeCompile

      - name: Upload Windows Native Executable
        uses: actions/upload-artifact@v4
        with:
          name: sec-tool-windows
          path: build/native/nativeCompile/sec-tool.exe

      - name: Upload to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: "Release ${{ github.ref_name }}"
          files: build/native/nativeCompile/sec-tool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
