name: Build Native Windows

on:
  push:
    branches: [ master ]

jobs:
  build-native:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: "21.0.0"
          java-version: "21"
          distribution: "graalvm"

      - name: Install Native Image
        shell: pwsh
        run: |
          $gu = & where.exe gu | Select-Object -First 1
          if ($gu) {
            & $gu install native-image
          } else {
            Write-Error "gu not found in PATH"
            exit 1
          }

      - name: Build Native Image
        run: ./gradlew nativeCompile